const $ = s => document.querySelector(s);
const fmt = (v,d=2)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const cls = v => Number(v)>=0?'pos':'neg';
let DATA=null;
const CHART_IDS=['SPX','SOX','TAIEX','NIKKEI','TOPIX','GOLD','WTI','USDTWD','USDJPY'];
let selectedCharts = JSON.parse(localStorage.getItem('gmmCharts')||'null') || ['SPX','TAIEX','NIKKEI','GOLD'];
let alerts = JSON.parse(localStorage.getItem('gmmAlerts')||'[]');

function drawLine(canvas, arr, opts={}){
  const dpr=devicePixelRatio||1, w=canvas.clientWidth||300, h=canvas.clientHeight||120;
  canvas.width=w*dpr; canvas.height=h*dpr; const c=canvas.getContext('2d'); c.scale(dpr,dpr); c.clearRect(0,0,w,h);
  if(!arr||arr.length<2)return; const min=Math.min(...arr), max=Math.max(...arr), pad=(max-min||1)*.15; const lo=min-pad, hi=max+pad;
  c.strokeStyle='#173b58'; c.lineWidth=1; for(let i=1;i<4;i++){const y=h*i/4;c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}
  c.strokeStyle=opts.color||'#22df91'; c.lineWidth=2; c.beginPath(); arr.forEach((v,i)=>{const x=i/(arr.length-1)*(w-8)+4; const y=h-((v-lo)/(hi-lo))*h; i?c.lineTo(x,y):c.moveTo(x,y)}); c.stroke();
}
function sparkSvg(arr,color){const w=160,h=34,min=Math.min(...arr),max=Math.max(...arr),r=max-min||1; const pts=arr.map((v,i)=>`${i/(arr.length-1)*w},${h-(v-min)/r*h}`).join(' ');return `<svg viewBox="0 0 ${w} ${h}" width="100%" height="32" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="2"/></svg>`}

function render(){ if(!DATA)return; $('#asof').textContent=new Date(DATA.asOf).toLocaleString('zh-TW');
  $('#topCards').innerHTML=DATA.top.map(x=>`<div class="card"><div class="label">${x.label}</div><div class="value">${fmt(x.value, x.id==='USDTWD'?3:2)}</div><div class="${cls(x.pct)}">${x.change>=0?'+':''}${fmt(x.change,x.id==='USDTWD'?3:2)}　${x.pct>=0?'+':''}${fmt(x.pct,2)}%</div><div class="spark">${sparkSvg(DATA.series[x.id]||[x.value],x.pct>=0?'#22df91':'#ff5b62')}</div></div>`).join('');
  $('#fxBody').innerHTML=DATA.fx.map(x=>`<tr><td>${x.pair}</td><td>${x.bid}</td><td>${x.ask}</td><td class="${cls(x.change)}">${x.change>=0?'+':''}${x.change}</td><td>${x.p1m}</td><td>${x.p3m}</td><td>${x.p6m}</td><td>${x.p1y}</td></tr>`).join('')+`<tr><td><b>USD/TWD Spot</b></td><td>${DATA.twd.spotBid}</td><td>${DATA.twd.spotAsk}</td><td>—</td><td colspan="4" class="source-note">Spot 與下方兩條 curve 分開顯示</td></tr><tr><td>↳ Offshore NDF (${DATA.twd.ndf.source})</td><td>—</td><td>—</td><td>—</td><td>${DATA.twd.ndf.p1m}</td><td>${DATA.twd.ndf.p3m}</td><td>${DATA.twd.ndf.p6m}</td><td>${DATA.twd.ndf.p1y}</td></tr><tr><td>↳ Onshore Fwd (${DATA.twd.onshore.source})</td><td>—</td><td>—</td><td>—</td><td>${DATA.twd.onshore.p1m}</td><td>${DATA.twd.onshore.p3m}</td><td>${DATA.twd.onshore.p6m}</td><td>${DATA.twd.onshore.p1y}</td></tr>`;
  $('#eqBody').innerHTML=DATA.equities.map(x=>`<tr><td>${x.name}<div class="source-note">${x.futureCode}</div></td><td>${fmt(x.cash)}</td><td>${fmt(x.future)}</td><td class="${cls(x.basis)}">${x.basis>=0?'+':''}${fmt(x.basis)}</td><td class="${cls(x.pct)}">${x.pct>=0?'+':''}${fmt(x.pct)}%</td></tr>`).join('');
  $('#cmdBody').innerHTML=DATA.commodities.map(x=>`<tr><td>${x.name}<div class="source-note">${x.futureCode}</div></td><td>${fmt(x.spot)}</td><td>${fmt(x.future)}</td><td class="${cls(x.basis)}">${x.basis>=0?'+':''}${fmt(x.basis)}</td><td class="${cls(x.pct)}">${x.pct>=0?'+':''}${fmt(x.pct)}%</td></tr>`).join('');
  $('#rateBody').innerHTML=DATA.rates.map(x=>`<tr><td>${x.name}</td><td>${fmt(x.rate)}%</td><td>${x.next}</td></tr>`).join('');
  renderYield(); renderChartChoices(); renderCharts(); renderAlerts(); evaluateAlerts();
}
function renderYield(){ drawLine($('#yieldCanvas'), DATA.ust.map(x=>x.yield), {color:'#56aef7'}); }
function renderChartChoices(){ $('#chartChoices').innerHTML=CHART_IDS.map(id=>`<label class="chip"><input type="checkbox" data-chart="${id}" ${selectedCharts.includes(id)?'checked':''}>${id}</label>`).join('')+`<span class="source-note">最多顯示 4 張</span>`; document.querySelectorAll('[data-chart]').forEach(cb=>cb.onchange=()=>{let id=cb.dataset.chart;if(cb.checked){if(selectedCharts.length>=4){cb.checked=false;return alert('最多同時顯示 4 張線圖');}selectedCharts.push(id)}else selectedCharts=selectedCharts.filter(x=>x!==id);localStorage.setItem('gmmCharts',JSON.stringify(selectedCharts));renderCharts();}); }
function renderCharts(){ const grid=$('#chartGrid'); grid.innerHTML=selectedCharts.map(id=>`<div class="chart-box"><div class="chart-head"><span>${id}</span><span>${fmt((DATA.series[id]||[]).slice(-1)[0]||0,id==='USDTWD'?3:2)}</span></div><canvas class="chart-canvas" data-line="${id}"></canvas></div>`).join(''); requestAnimationFrame(()=>document.querySelectorAll('[data-line]').forEach(c=>drawLine(c,DATA.series[c.dataset.line],{color:'#22df91'}))); }
function symbolMap(){ const m={GOLD:DATA.commodities[0].spot,SILVER:DATA.commodities[1].spot,WTI:DATA.commodities[2].spot,BRENT:DATA.commodities[3].spot,USDTWD:DATA.twd.spotBid,USDTWD_1M:DATA.twd.ndf.p1m,USDTWD_3M:DATA.twd.ndf.p3m,SPX:DATA.equities[0].cash,SOX:DATA.equities[2].cash,TAIEX:DATA.equities[3].cash,NIKKEI:DATA.equities[4].cash,TOPIX:DATA.equities[5].cash}; DATA.ust.forEach(x=>m['US'+x.tenor.replace('M','M').replace('Y','Y')]=x.yield); return m; }
function evalFormula(s){ const comp=s.match(/(.+?)(>=|<=|>|<|==)(.+)/); if(!comp)return {ok:false,error:'格式需包含 >、<、>=、<='}; const vars=symbolMap(); const evalSide=t=>{ let e=t.toUpperCase(); Object.keys(vars).sort((a,b)=>b.length-a.length).forEach(k=>e=e.replaceAll(k,String(vars[k]))); if(!/^[0-9+\-*/().\s]+$/.test(e))throw new Error('含未知代碼'); return Function('"use strict";return ('+e+')')(); }; try{const l=evalSide(comp[1]),r=evalSide(comp[3]); const op=comp[2]; return {ok:true,hit:({'>':l>r,'<':l<r,'>=':l>=r,'<=':l<=r,'==':l==r})[op],left:l,right:r};}catch(e){return {ok:false,error:e.message};} }
function renderAlerts(){ $('#alertList').innerHTML=alerts.length?alerts.map((a,i)=>{const r=evalFormula(a.formula);return `<div class="alert-item"><span>${a.formula} <small class="source-note">${r.ok?(r.hit?'條件成立':'未觸發'):'公式錯誤'}</small></span><button data-del="${i}">刪除</button></div>`}).join(''):`<div class="source-note">尚未建立警示。可輸入：GOLD/SILVER > 90</div>`; document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{alerts.splice(+b.dataset.del,1);saveAlerts();renderAlerts();}); }
function saveAlerts(){localStorage.setItem('gmmAlerts',JSON.stringify(alerts))}
function evaluateAlerts(){ alerts.forEach(a=>{const r=evalFormula(a.formula); if(!r.ok||!r.hit)return; const now=Date.now(), cd=(a.cooldown||0)*1000; if(a.lastHit && (cd===0 || now-a.lastHit<cd))return; a.lastHit=now; saveAlerts(); if(Notification.permission==='granted') new Notification('Global Market Monitor',{body:`警示觸發：${a.formula}`}); }); }
$('#addAlert').onclick=()=>{const f=$('#formulaInput').value.trim(); if(!f)return; const test=evalFormula(f); if(!test.ok)return alert('公式無法解析：'+test.error); alerts.push({formula:f,cooldown:+$('#cooldown').value,lastHit:0}); saveAlerts(); $('#formulaInput').value=''; renderAlerts();};
$('#notifyBtn').onclick=async()=>{if(!('Notification'in window))return alert('此瀏覽器不支援通知'); const p=await Notification.requestPermission(); alert(p==='granted'?'通知已啟用':'通知未啟用');};
async function refresh(){try{$('#feedStatus').textContent='更新中';const raw=await MarketProviders.load(); DATA=MarketProviders.simulate(raw); $('#feedStatus').textContent='資料已更新';render();}catch(e){console.error(e);$('#feedStatus').textContent='資料讀取失敗';}}
refresh(); setInterval(refresh,(window.MARKET_MONITOR_CONFIG?.refreshMs)||15000); window.addEventListener('resize',()=>{if(DATA){renderYield();renderCharts();}});
