window.MarketProviders = (() => {
  const cfg=()=>window.MARKET_MONITOR_CONFIG||{mode:'local-json',endpoint:'./data/latest.json',refreshMs:15000,demoSimulation:false,liveEndpoint:''};
  async function fetchJson(url,required=true){if(!url)return null;try{const r=await fetch(url+(url.includes('?')?'&':'?')+'t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}catch(e){if(required)throw e;console.warn('Optional market data unavailable:',url,e);return null}}
  function applyContracts(leg,p,source,mode){if(!p?.contracts?.length)return;const contracts=p.contracts.map(c=>({month:c.month,date:c.date||null,session:c.session||null,bid:c.bid??null,ask:c.ask??null,last:c.last??null,settlement:c.settlement??null,volume:c.volume??null,openInterest:c.openInterest??null,timestamp:c.timestamp||null}));const selected=contracts.find(c=>c.month===p.defaultMonth)||contracts[0];leg.contracts=contracts;leg.actualMonths=contracts.map(c=>c.month);leg.expiry=selected?.month||leg.expiry;if(selected?.bid!=null)leg.bid=selected.bid;if(selected?.ask!=null)leg.ask=selected.ask;if(selected?.last!=null)leg.last=selected.last;leg.quoteDate=selected?.date||null;leg.quoteSession=selected?.session||null;leg.quoteTimestamp=selected?.timestamp||null;leg.source=source;leg.quoteMode=mode}
  function mergeTaifex(data,official){if(!official?.products||!Array.isArray(data?.crossMarketCatalog))return data;data.taifexMeta=official.meta||null;for(const row of data.crossMarketCatalog){const a=official.products[row?.tw?.code];if(a)applyContracts(row.tw,a,'TAIFEX OpenAPI','OFFICIAL DAILY');if(String(row?.os?.exchange||'').includes('TAIFEX')){const b=official.products[row?.os?.code];if(b)applyContracts(row.os,b,'TAIFEX OpenAPI','OFFICIAL DAILY')}}return data}
  function mergeDelayed(data,delayed){if(!delayed?.products||!Array.isArray(data?.crossMarketCatalog))return data;data.delayedMeta=delayed.meta||null;for(const row of data.crossMarketCatalog){for(const leg of [row.tw,row.os]){if(!leg||String(leg.exchange||'').includes('TAIFEX'))continue;const p=delayed.products[leg.id]||delayed.products[leg.code];if(p?.contracts?.length)applyContracts(leg,p,p.source||'Delayed feed',p.mode||'DELAYED')}}return data}
  function localLiveEndpoint(){try{const s=JSON.parse(localStorage.getItem('gmmMarketConnectionsV1')||'{}');if(!s.preferLive||!s.activeBroker)return '';return s.brokers?.[s.activeBroker]?.endpoint||''}catch{return ''}}
  function mergeLive(data,live){if(!live?.quotes||!Array.isArray(data?.crossMarketCatalog))return data;data.liveMeta=live.meta||null;for(const row of data.crossMarketCatalog){for(const leg of [row.tw,row.os]){if(!leg||String(leg.exchange||'').includes('TAIFEX'))continue;const p=live.quotes[leg.id]||live.quotes[leg.code];if(p)applyContracts(leg,p,p.source||leg.exchange||'Licensed feed','LIVE')}}return data}
  async function load(){const c=cfg(),endpoint=c.endpoint||'./data/latest.json';const [base,taifex,delayed,live]=await Promise.all([fetchJson(endpoint,true),fetchJson('./data/taifex-latest.json',false),fetchJson('./data/overseas-delayed.json',false),fetchJson(localLiveEndpoint()||c.liveEndpoint,false)]);mergeTaifex(base,taifex);mergeDelayed(base,delayed);mergeLive(base,live);return base}
  function simulate(data){if(!cfg().demoSimulation)return data;const copy=structuredClone(data),j=(v,s=.0006)=>v*(1+(Math.random()-.5)*s);copy.asOf=new Date().toISOString();copy.top.forEach(x=>x.value=j(x.value));return copy}
  return {load,simulate};
})();
